app:
    resource: "@AppBundle/Controller/"
    type:     annotation

orders:
    type: rest
    prefix: /api
    resource: AppBundle\Controller\OrderController

rest:
    type: rest
    prefix: /api
    resource: AppBundle\Controller\RestController
