app:
    resource: "@AppBundle/Controller/"
    type:     annotation

customers:
    type: rest
    prefix: /api
    resource: AppBundle\Controller\CustomerController

orders:
    type: rest
    prefix: /api
    resource: AppBundle\Controller\OrderController

toppings:
    type: rest
    prefix: /api
    resource: AppBundle\Controller\ToppingController

rest:
    type: rest
    prefix: /api
    resource: AppBundle\Controller\RestController
