app:
    resource: "@AppBundle/Controller/"
    type:     annotation

rest:
    type: rest
    resource: AppBundle\Controller\RestController

orders:
    type: rest
    resource: AppBundle\Controller\OrderController
